import Head from "next/head";
import Image from "next/image";
import style from "@/styles/pages/home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <section className={`container-fluid ${style.homePage}`}>
          <div className={`container`}>
            <div className={`row`}>
              <div className={`col-12 position-relative ${style.cardHolder}`}>
                {/* ICON AND BUTTON LOGIN OR REGISTER */}
                <div
                  className={`position-absolute top-0 start-50 translate-middle-x p-0 ${style.iconBtnAuth}`}
                >
                  {/* TITLE CARD */}
                  <div className={`row ${style.titleCard}`}>
                    <div className={`col`}>
                      <div className="d-flex justify-content-between">
                        <Image
                          src={require("/public/images/Icon-app-nooutline.png")}
                          className={` ${style.iconApp}`}
                          // width={500}
                          height={65}
                          alt="Icon-Linkpocket"
                        />
                        <div className={` ${style.btnLoginRegister}`}>
                          <button
                            type="button"
                            className={`btn btn-outline-primary ${style.btnLogin}`}
                          >
                            Login
                          </button>
                          <button
                            type="button"
                            className={`btn btn-primary ${style.btnRegister}`}
                          >
                            Register
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {/* CARD FORM REGISTER */}
                <div
                  className={`position-absolute top-50 start-50 translate-middle p-4 ${style.cardLinkPocket}`}
                >
                  <div className={`row ${style.profileCard}`}>
                    <div className="col-4">
                      <Image
                        src={require("/public/images/IMG_20230116_093528.jpg")}
                        className={` ${style.photoProfile}`}
                        // width={500}
                        // height={65}
                        alt="Icon-Linkpocket"
                      />
                    </div>
                    <div className="col-8">
                      <h3 className={`${style.username}`}>Maulana Ismail</h3>
                      <p className={`${style.desc}`}>
                        Terjemahkan teks & berkas dokumen secara instan.
                        Terjemahan.
                      </p>
                      <div className="d-grid gap-2">
                        <button
                          type="button"
                          className={`btn btn-primary ${style.btnShare}`}
                        >
                          Share your Linkpocket card
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
