import React from "react";
import Head from "next/head";
import style from "@/styles/pages/setupPage.module.scss";
import Image from "next/image";

// MATERIAL UI
import Box from "@mui/material/Box";
import Input from "@mui/material/Input";
import InputLabel from "@mui/material/InputLabel";
import InputAdornment from "@mui/material/InputAdornment";
import FormControl from "@mui/material/FormControl";
import TextField from "@mui/material/TextField";

// ICON
import FacebookIcon from "@mui/icons-material/Facebook";
import GitHubIcon from "@mui/icons-material/GitHub";
import YouTubeIcon from "@mui/icons-material/YouTube";
import WhatsAppIcon from "@mui/icons-material/WhatsApp";
import TwitterIcon from "@mui/icons-material/Twitter";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import InstagramIcon from "@mui/icons-material/Instagram";

export default function SetupLinkPocket() {
  const [addPhotoName, setAddPhotoName] = React.useState(true);
  const [addDesc, setAddDesc] = React.useState(false);
  const [addListLink, setAddListLink] = React.useState(false);

  // FORM LIST LINK SOCIAL MEDIA
  const [choose, setChoose] = React.useState(false);
  const [formFacebook, setFormFacebook] = React.useState(false);
  const [formInstagram, setFormInstagram] = React.useState(false);
  const [formTikTok, setFormTikTok] = React.useState(false);
  const [formWhatsApp, setFormWhatsApp] = React.useState(false);
  const [formYoutube, setFormYoutube] = React.useState(false);
  const [formTwitter, setFormTwitter] = React.useState(false);
  const [formGitHub, setFormGitHub] = React.useState(false);
  const [formLinkedIn, setFormLinkedIn] = React.useState(false);
  const [formShopee, setFormShopee] = React.useState(false);
  const [formAnother, setFormAnother] = React.useState(false);

  return (
    <div>
      <>
        <Head>
          <title>SetUp | LinkPocket</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={style.main}>
          <section className={`container-fluid ${style.setup}`}>
            <div className={`container`}>
              <div className={`row`}>
                <div className={`col-12 position-relative ${style.setUpSide}`}>
                  <div className="position-absolute top-50 start-0 translate-middle-y">
                    {!addListLink ? (
                      <>
                        <Image
                          src={require("/public/images/Icon-app-outline.png")}
                          className={`${style.iconApp}`}
                          // width={500}
                          height={75}
                          alt="Icon-Linkpocket"
                        />
                        <h1 className={`${style.Title}`}>
                          Hello Maulana Ismail
                        </h1>
                      </>
                    ) : null}

                    {/* SUB TITLE ADD PHOTO PROFILE AND NAME */}
                    {addPhotoName ? (
                      <p className={`${style.subTitle}`}>
                        First of all add a Profile Photo and a name for your
                        LinkPocket.
                      </p>
                    ) : null}
                    {/* END OF SUB TITLE ADD DESCRIPTION */}

                    {/* SUB TITLE ADD DESCRIPTION */}
                    {addDesc ? (
                      <p className={`${style.subTitle}`}>
                        Next, add a description for your LinkPocket.
                      </p>
                    ) : null}
                    {/* END OF SUB TITLE ADD DESCRIPTION */}

                    {/* CARD ADD PHOTO PROFILE AND NAME */}
                    {addPhotoName ? (
                      <>
                        <div
                          className={`px-sm-4 py-4 px-4  ${style.cardSetUp}`}
                        >
                          {/* TITLE CARD */}
                          <div className={`row ${style.titleCard}`}>
                            <div className={`col-5`}>
                              <Image
                                src={require("/public/images/IMG_20230116_093528.jpg")}
                                className={` ${style.addPhotoProfile}`}
                                // width={500}
                                // height={65}
                                alt="Icon-Linkpocket"
                              />
                              <p className={`${style.rulesPhoto}`}>
                                *1/1 ratio recommended
                              </p>
                            </div>
                            <div className="col-7 position-relative">
                              <div className="position-absolute top-0 start-0">
                                <label>Your LinkPocket name</label>
                                <input
                                  type="text"
                                  className={`${style.formAddName}`}
                                  // onChange={(e) => setEmail(e.target.value)}
                                  // onKeyDown={(event) => {
                                  //   if (event.key === "Enter") {
                                  //     handleSubmit;
                                  //   }
                                  // }}
                                />
                                <p className={`${style.rulesForm}`}>
                                  *Maximum 20 characters length
                                </p>
                              </div>
                              <div className="position-absolute bottom-0 end-0">
                                <button
                                  className={`${style.btnNext}`}
                                  onClick={() => {
                                    setAddDesc(true);
                                    setAddPhotoName(false);
                                  }}
                                  // disabled={isLoading}
                                >
                                  {"Next ->"}
                                </button>
                              </div>
                            </div>
                          </div>
                        </div>
                        <p className={`${style.Announcement}`}>
                          *You can change photos and names later on the edit
                          menu
                        </p>
                      </>
                    ) : null}
                    {/* END OF ADD CARD PHOTO PROFILE AND NAME */}

                    {/* CARD ADD DESCRIPTION */}
                    {addDesc ? (
                      <>
                        <div
                          className={`px-sm-4 py-4 px-4 ${style.cardSetUpDesc}`}
                        >
                          {/* TITLE CARD */}
                          <div className={`row ${style.titleCard}`}>
                            <div className={`col-5`}>
                              <Image
                                src={require("/public/images/IMG_20230116_093528.jpg")}
                                className={` ${style.addPhotoProfile}`}
                                // width={500}
                                // height={65}
                                alt="Icon-Linkpocket"
                              />
                            </div>
                            <div className="col-7 position-relative">
                              <div className="position-absolute top-0 start-0">
                                <label>Your LinkPocket description</label>
                                <textarea
                                  type="textarea"
                                  className={`${style.formAddDesc}`}
                                  maxlength="60"
                                  // onChange={(e) => setEmail(e.target.value)}
                                  // onKeyDown={(event) => {
                                  //   if (event.key === "Enter") {
                                  //     handleSubmit;
                                  //   }
                                  // }}
                                />
                                <style>
                                  {`
                                    ::-webkit-scrollbar {
                                      width: 0.3em;
                                      height: 0.5em;
                                    }
                                    ::-webkit-scrollbar-thumb {
                                      background-color: rgba(0, 0, 0, 0.2);
                                    }
                                  `}
                                </style>
                                <p className={`${style.rulesForm}`}>
                                  *Maximum 60 characters length
                                </p>
                              </div>
                              <div className="position-absolute bottom-0 end-0">
                                <button
                                  className={`${style.btnNext}`}
                                  onClick={() => {
                                    setAddDesc(false);
                                    setAddPhotoName(true);
                                  }}
                                  // disabled={isLoading}
                                >
                                  {"<- Back"}
                                </button>
                                <button
                                  className={`${style.btnNext}`}
                                  onClick={() => {
                                    setAddDesc(false);
                                    setAddPhotoName(false);
                                    setAddListLink(true);
                                  }}
                                  // disabled={isLoading}
                                >
                                  {"Next ->"}
                                </button>
                              </div>
                            </div>
                          </div>
                        </div>
                        <p className={`${style.Announcement}`}>
                          *You can change description later on the edit menu
                        </p>
                      </>
                    ) : null}
                    {/* END OF ADD DESCRIPTION */}

                    {addListLink ? (
                      <>
                        <div className={`container ${style.addListLinkPage}`}>
                          <div className="row ">
                            <div
                              className={`col-sm-7 col-12 ${style.optionSide}`}
                            >
                              <div className="">
                                <Image
                                  src={require("/public/images/Icon-app-outline.png")}
                                  className={`${style.iconApp}`}
                                  // width={500}
                                  height={75}
                                  alt="Icon-Linkpocket"
                                />
                                <h1 className={`${style.Title}`}>
                                  Hello Maulana Ismail
                                </h1>
                              </div>

                              {/* SUB TITLE ADD LIST LINK */}
                              <p
                                className={`${style.subTitle}`}
                              >
                                The final step, directly add your social media
                                links and other pages.
                              </p>
                              {/* END OF SUB TITLE ADD LIST LINK */}

                              {/* CARD ADD LIST LINK */}
                              <div
                                className={`px-sm-4 py-4 px-4 ${style.cardOptionLink}`}
                              >
                                {/* TITLE CARD */}
                                <div className={`row ${style.titleCard}`}>
                                  <div className={`col-12`}>
                                    <p>
                                      Choose social media or something else to
                                      save your link
                                    </p>
                                  </div>
                                </div>

                                {/* BUTTON OPTION APP */}
                                <div className={`row ${style.option}`}>
                                  <div className="col text-center">
                                    {/* FACEBOOK */}
                                    <button
                                      // className={`btn btn-outline-primary ${style.btnOption}`}
                                      className={`btn btn-outline-primary ${
                                        formFacebook
                                          ? style.selected
                                          : style.btnOption
                                      }`}
                                      onClick={() => {
                                        if (formFacebook === false) {
                                          setFormFacebook(true);
                                        } else {
                                          setFormFacebook(false);
                                        }
                                      }}
                                      // disabled={isLoading}
                                    >
                                      {/* <Image
                                        src={require("../../../public/images/icon-fb.png")}
                                        className={`${style.iconSocmed}`}
                                        // width={500}
                                        height={31}
                                        alt="Icon-Linkpocket"
                                      /> */}
                                      <FacebookIcon
                                        style={{
                                          color: "#4267B2",
                                          fontSize: "30px",
                                        }}
                                      />{" "}
                                      Facebook
                                    </button>

                                    {/* GITHUB */}
                                    <button
                                      className={`btn btn-outline-primary ${
                                        formGitHub
                                          ? style.selected
                                          : style.btnOption
                                      }`}
                                      onClick={() => {
                                        if (formGitHub === false) {
                                          setFormGitHub(true);
                                        } else {
                                          setFormGitHub(false);
                                        }
                                      }}
                                      // disabled={isLoading}
                                    >
                                      {/* <Image
                                        src={require("../../../public/images/icon-gh.png")}
                                        className={`${style.iconSocmed}`}
                                        style={{
                                          marginRight: "3px",
                                          letterSpacing: "0",
                                        }}
                                        // width={500}
                                        height={28}
                                        alt="Icon-Linkpocket"
                                      /> */}
                                      <GitHubIcon
                                        style={{
                                          color: "#333",
                                          fontSize: "29px",
                                        }}
                                      />{" "}
                                      GitHub
                                    </button>

                                    {/* YOUTUBE */}
                                    <button
                                      className={`btn btn-outline-primary ${
                                        formYoutube
                                          ? style.selected
                                          : style.btnOption
                                      }`}
                                      onClick={() => {
                                        if (formYoutube === false) {
                                          setFormYoutube(true);
                                        } else {
                                          setFormYoutube(false);
                                        }
                                      }}
                                      // disabled={isLoading}
                                    >
                                      {/* <Image
                                        src={require("../../../public/images/icon-yt.png")}
                                        className={`${style.iconSocmed}`}
                                        // width={500}
                                        height={27}
                                        alt="Icon-Linkpocket"
                                      /> */}
                                      <YouTubeIcon
                                        style={{
                                          color: "#FF0000",
                                          fontSize: "31px",
                                        }}
                                      />{" "}
                                      YouTube
                                    </button>

                                    {/* TIKTOK */}
                                    <button
                                      className={`btn btn-outline-primary ${
                                        formTikTok
                                          ? style.selected
                                          : style.btnOption
                                      }`}
                                      onClick={() => {
                                        if (formTikTok === false) {
                                          setFormTikTok(true);
                                        } else {
                                          setFormTikTok(false);
                                        }
                                      }}
                                      // disabled={isLoading}
                                    >
                                      <Image
                                        src={require("../../../public/images/icon-tiktok.png")}
                                        className={`${style.iconSocmed}`}
                                        // width={500}
                                        height={29}
                                        alt="Icon-Linkpocket"
                                      />
                                      TikTok
                                    </button>

                                    {/* WHATSAPP */}
                                    <button
                                      className={`btn btn-outline-primary ${
                                        formWhatsApp
                                          ? style.selected
                                          : style.btnOption
                                      }`}
                                      onClick={() => {
                                        if (formWhatsApp === false) {
                                          setFormWhatsApp(true);
                                        } else {
                                          setFormWhatsApp(false);
                                        }
                                      }}
                                      // disabled={isLoading}
                                    >
                                      {/* <Image
                                        src={require("../../../public/images/icon-wa.png")}
                                        className={`${style.iconSocmed}`}
                                        // width={500}
                                        height={28}
                                        alt="Icon-Linkpocket"
                                      /> */}
                                      <WhatsAppIcon
                                        style={{
                                          color: "#25D366",
                                          fontSize: "29px",
                                        }}
                                      />{" "}
                                      WhatsApp
                                    </button>

                                    {/* TWITTER */}
                                    <button
                                      className={`btn btn-outline-primary ${
                                        formTwitter
                                          ? style.selected
                                          : style.btnOption
                                      }`}
                                      onClick={() => {
                                        if (formTwitter === false) {
                                          setFormTwitter(true);
                                        } else {
                                          setFormTwitter(false);
                                        }
                                      }}
                                      // disabled={isLoading}
                                    >
                                      {/* <Image
                                        src={require("../../../public/images/icon-twt.png")}
                                        className={`${style.iconSocmed}`}
                                        style={{
                                          marginRight: "7px",
                                          letterSpacing: "0",
                                        }}
                                        // width={500}
                                        height={27}
                                        alt="Icon-Linkpocket"
                                      /> */}
                                      <TwitterIcon
                                        style={{
                                          color: "#1DA1F2",
                                          fontSize: "29px",
                                        }}
                                      />{" "}
                                      Twitter
                                    </button>

                                    {/* LINKEDIN */}
                                    <button
                                      className={`btn btn-outline-primary ${
                                        formLinkedIn
                                          ? style.selected
                                          : style.btnOption
                                      }`}
                                      onClick={() => {
                                        if (formLinkedIn === false) {
                                          setFormLinkedIn(true);
                                        } else {
                                          setFormLinkedIn(false);
                                        }
                                      }}
                                      // disabled={isLoading}
                                    >
                                      {/* <Image
                                        src={require("../../../public/images/icon-li.png")}
                                        className={`${style.iconSocmed}`}
                                        style={{
                                          marginRight: "3px",
                                          letterSpacing: "0",
                                        }}
                                        // width={500}
                                        height={28}
                                        alt="Icon-Linkpocket"
                                      /> */}
                                      <LinkedInIcon
                                        style={{
                                          color: "#0072b1",
                                          fontSize: "29px",
                                        }}
                                      />{" "}
                                      LinkedIn
                                    </button>

                                    {/* INSTAGRAM */}
                                    <button
                                      className={`btn btn-outline-primary ${
                                        formInstagram
                                          ? style.selected
                                          : style.btnOption
                                      }`}
                                      onClick={() => {
                                        if (formInstagram === false) {
                                          setFormInstagram(true);
                                        } else {
                                          setFormInstagram(false);
                                        }
                                      }}
                                      // disabled={isLoading}
                                    >
                                      {/* <Image
                                        src={require("../../../public/images/icon-ig.png")}
                                        className={`${style.iconSocmed}`}
                                        style={{
                                          marginRight: "0",
                                          letterSpacing: "0",
                                        }}
                                        // width={500}
                                        height={27}
                                        alt="Icon-Linkpocket"
                                      /> */}
                                      <InstagramIcon
                                        style={{
                                          color: "#E1306C",
                                          fontSize: "29px",
                                        }}
                                      />{" "}
                                      Instagram
                                    </button>

                                    {/* SHOPEE */}
                                    <button
                                      className={`btn btn-outline-primary ${
                                        formShopee
                                          ? style.selected
                                          : style.btnOption
                                      }`}
                                      onClick={() => {
                                        if (formShopee === false) {
                                          setFormShopee(true);
                                        } else {
                                          setFormShopee(false);
                                        }
                                      }}
                                      // disabled={isLoading}
                                    >
                                      <Image
                                        src={require("../../../public/images/icon-sp.png")}
                                        className={`${style.iconSocmed}`}
                                        style={{
                                          marginRight: "7px",
                                          letterSpacing: "0",
                                        }}
                                        // width={500}
                                        height={27}
                                        alt="Icon-Linkpocket"
                                      />
                                      Shopee
                                    </button>

                                    {/* ANOTHER */}
                                    <button
                                      className={`btn btn-outline-primary ${
                                        formAnother
                                          ? style.selected
                                          : style.btnOption
                                      }`}
                                      style={{
                                        padding: "5px 50px",
                                      }}
                                      onClick={() => {
                                        if (formAnother === false) {
                                          setFormAnother(true);
                                        } else {
                                          setFormAnother(false);
                                        }
                                      }}
                                      // disabled={isLoading}
                                    >
                                      +
                                    </button>
                                  </div>
                                </div>
                                {/* END OF BUTTON OPTION APP */}
                              </div>
                              {/* END OF ADD LIST LINK */}
                            </div>
                            <div
                              className={`col-sm-5 col-12 d-flex align-items-center ${style.listLinkSide}`}
                            >
                              <div className="row">
                                <div className="col-12">
                                  <div
                                    className={`px-sm-3 py-4 px-4 ${style.cardFormLink}`}
                                  >
                                    <p className={`${style.titleCard}`}>
                                      Enter your link
                                    </p>
                                    <div className={`${style.form}`}>
                                      <Box
                                        sx={{
                                          "& > :not(style)": { m: 1 },
                                        }}
                                      >
                                        {/* FACEBOOK */}
                                        {formFacebook ? (
                                          <>
                                            <Box
                                              sx={{
                                                display: "flex",
                                                alignItems: "flex-end",
                                                "& > :not(style)": { mb: 2 },
                                              }}
                                            >
                                              {/* <Image
                                                src={require("../../../public/images/icon-fb.png")}
                                                className={`${style.iconSocmed}`}
                                                style={{ marginRight: "5px" }}
                                                // width={500}
                                                height={40}
                                                alt="Icon-Linkpocket"
                                              /> */}
                                              <FacebookIcon
                                                style={{
                                                  color: "#4267B2",
                                                  fontSize: "40px",
                                                  marginRight: "5px",
                                                }}
                                              />
                                              <TextField
                                                className={style.formFb}
                                                id="outlined-search"
                                                label="Facebook"
                                                size="small"
                                                type="Required"
                                                // color="primary"
                                                sx={{
                                                  width: "100%",
                                                }}
                                              />
                                            </Box>
                                          </>
                                        ) : null}

                                        {/* INSTAGRAM */}
                                        {formInstagram ? (
                                          <>
                                            <Box
                                              sx={{
                                                display: "flex",
                                                alignItems: "flex-end",
                                                "& > :not(style)": { mb: 2 },
                                              }}
                                            >
                                              {/* <Image
                                                src={require("../../../public/images/icon-fb.png")}
                                                className={`${style.iconSocmed}`}
                                                style={{ marginRight: "5px" }}
                                                // width={500}
                                                height={40}
                                                alt="Icon-Linkpocket"
                                              /> */}
                                              <InstagramIcon
                                                style={{
                                                  color: "#E1306C",
                                                  fontSize: "40px",
                                                  marginRight: "5px",
                                                }}
                                              />
                                              <TextField
                                                id="outlined-search"
                                                label="Instagram"
                                                size="small"
                                                type="Required"
                                                color="primary"
                                                sx={{
                                                  width: "100%",
                                                }}
                                              />
                                            </Box>
                                          </>
                                        ) : null}

                                        {/* TIKTOK */}
                                        {formTikTok ? (
                                          <>
                                            <Box
                                              sx={{
                                                display: "flex",
                                                alignItems: "flex-end",
                                                "& > :not(style)": { mb: 2 },
                                              }}
                                            >
                                              <Image
                                                src={require("../../../public/images/icon-tiktok.png")}
                                                className={`${style.iconSocmed}`}
                                                style={{
                                                  marginRight: "6px",
                                                  marginLeft: "2px",
                                                }}
                                                // width={500}
                                                height={37}
                                                alt="Icon-Linkpocket"
                                              />
                                              <TextField
                                                id="outlined-search"
                                                label="TikTok"
                                                size="small"
                                                type="Required"
                                                color="primary"
                                                sx={{
                                                  width: "100%",
                                                }}
                                              />
                                            </Box>
                                          </>
                                        ) : null}

                                        {/* WHATSAPP */}
                                        {formWhatsApp ? (
                                          <>
                                            <Box
                                              sx={{
                                                display: "flex",
                                                alignItems: "flex-end",
                                                "& > :not(style)": { mb: 2 },
                                              }}
                                            >
                                              {/* <Image
                                                src={require("../../../public/images/icon-fb.png")}
                                                className={`${style.iconSocmed}`}
                                                style={{ marginRight: "5px" }}
                                                // width={500}
                                                height={40}
                                                alt="Icon-Linkpocket"
                                              /> */}
                                              <WhatsAppIcon
                                                style={{
                                                  color: "#25D366",
                                                  fontSize: "40px",
                                                  marginRight: "5px",
                                                }}
                                              />
                                              <TextField
                                                id="outlined-search"
                                                label="WhatsApp"
                                                size="small"
                                                type="Required"
                                                color="primary"
                                                sx={{
                                                  width: "100%",
                                                }}
                                              />
                                            </Box>
                                          </>
                                        ) : null}

                                        {/* YOUTUBE */}
                                        {formYoutube ? (
                                          <>
                                            <Box
                                              sx={{
                                                display: "flex",
                                                alignItems: "flex-end",
                                                "& > :not(style)": { mb: 2 },
                                              }}
                                            >
                                              {/* <Image
                                                src={require("../../../public/images/icon-fb.png")}
                                                className={`${style.iconSocmed}`}
                                                style={{ marginRight: "5px" }}
                                                // width={500}
                                                height={40}
                                                alt="Icon-Linkpocket"
                                              /> */}
                                              <YouTubeIcon
                                                style={{
                                                  color: "#FF0000",
                                                  fontSize: "40px",
                                                  marginRight: "5px",
                                                }}
                                              />
                                              <TextField
                                                id="outlined-search"
                                                label="YouTube"
                                                size="small"
                                                type="Required"
                                                color="primary"
                                                sx={{
                                                  width: "100%",
                                                }}
                                              />
                                            </Box>
                                          </>
                                        ) : null}

                                        {/* TWITTER */}
                                        {formTwitter ? (
                                          <>
                                            <Box
                                              sx={{
                                                display: "flex",
                                                alignItems: "flex-end",
                                                "& > :not(style)": { mb: 2 },
                                              }}
                                            >
                                              {/* <Image
                                                src={require("../../../public/images/icon-fb.png")}
                                                className={`${style.iconSocmed}`}
                                                style={{ marginRight: "5px" }}
                                                // width={500}
                                                height={40}
                                                alt="Icon-Linkpocket"
                                              /> */}
                                              <TwitterIcon
                                                style={{
                                                  color: "#1DA1F2",
                                                  fontSize: "40px",
                                                  marginRight: "5px",
                                                }}
                                              />
                                              <TextField
                                                id="outlined-search"
                                                label="Twitter"
                                                size="small"
                                                type="Required"
                                                color="primary"
                                                sx={{
                                                  width: "100%",
                                                }}
                                              />
                                            </Box>
                                          </>
                                        ) : null}

                                        {/* GITHUB */}
                                        {formGitHub ? (
                                          <>
                                            <Box
                                              sx={{
                                                display: "flex",
                                                alignItems: "flex-end",
                                                "& > :not(style)": { mb: 2 },
                                              }}
                                            >
                                              {/* <Image
                                                src={require("../../../public/images/icon-fb.png")}
                                                className={`${style.iconSocmed}`}
                                                style={{ marginRight: "5px" }}
                                                // width={500}
                                                height={40}
                                                alt="Icon-Linkpocket"
                                              /> */}
                                              <GitHubIcon
                                                style={{
                                                  color: "#333",
                                                  fontSize: "40px",
                                                  marginRight: "5px",
                                                }}
                                              />
                                              <TextField
                                                id="outlined-search"
                                                label="GitHub"
                                                size="small"
                                                type="Required"
                                                color="primary"
                                                sx={{
                                                  width: "100%",
                                                }}
                                              />
                                            </Box>
                                          </>
                                        ) : null}

                                        {/* LINKEDIN */}
                                        {formLinkedIn ? (
                                          <>
                                            <Box
                                              sx={{
                                                display: "flex",
                                                alignItems: "flex-end",
                                                "& > :not(style)": { mb: 2 },
                                              }}
                                            >
                                              {/* <Image
                                                src={require("../../../public/images/icon-fb.png")}
                                                className={`${style.iconSocmed}`}
                                                style={{ marginRight: "5px" }}
                                                // width={500}
                                                height={40}
                                                alt="Icon-Linkpocket"
                                              /> */}
                                              <LinkedInIcon
                                                style={{
                                                  color: "#0072b1",
                                                  fontSize: "40px",
                                                  marginRight: "5px",
                                                }}
                                              />
                                              <TextField
                                                id="outlined-search"
                                                label="LinkedIn"
                                                size="small"
                                                type="Required"
                                                color="primary"
                                                sx={{
                                                  width: "100%",
                                                }}
                                              />
                                            </Box>
                                          </>
                                        ) : null}

                                        {/* SHOPEE */}
                                        {formShopee ? (
                                          <>
                                            <Box
                                              sx={{
                                                display: "flex",
                                                alignItems: "flex-end",
                                                "& > :not(style)": { mb: 2 },
                                              }}
                                            >
                                              <Image
                                                src={require("../../../public/images/icon-sp.png")}
                                                className={`${style.iconSocmed}`}
                                                style={{ marginRight: "5px" }}
                                                // width={500}
                                                height={40}
                                                alt="Icon-Linkpocket"
                                              />
                                              <TextField
                                                id="outlined-search"
                                                label="Shopee"
                                                size="small"
                                                type="Required"
                                                color="primary"
                                                sx={{
                                                  width: "100%",
                                                }}
                                              />
                                            </Box>
                                          </>
                                        ) : null}

                                        {/* ANOTHER */}
                                        {formAnother ? (
                                          <>
                                            <Box
                                              sx={{
                                                display: "flex",
                                                alignItems: "flex-end",
                                                "& > :not(style)": { mb: 2 },
                                              }}
                                            >
                                              <Image
                                                src={require("../../../public/images/icon-fb.png")}
                                                className={`${style.iconSocmed}`}
                                                style={{ marginRight: "5px" }}
                                                // width={500}
                                                height={40}
                                                alt="Icon-Linkpocket"
                                              />
                                              <TextField
                                                id="outlined-search"
                                                label="Another"
                                                size="small"
                                                type="Required"
                                                color="primary"
                                                sx={{
                                                  width: "100%",
                                                }}
                                              />
                                            </Box>
                                          </>
                                        ) : null}
                                      </Box>
                                      <style>
                                        {`
                                        ::-webkit-scrollbar {
                                          width: 0.5em;
                                          height: 0.5em;
                                        }
                                        ::-webkit-scrollbar-thumb {
                                          background-color: rgba(0, 0, 0, 0.2);
                                        }
                                      `}
                                      </style>
                                    </div>
                                    <p className={`${style.Announcement}`}>
                                      *You can change information later on the
                                      edit menu
                                    </p>
                                    {/* BUTTON BACK OR SKIP AND SAVE */}
                                    <div className="text-center">
                                      <button
                                        className={`${style.btnNext}`}
                                        onClick={() => {
                                          setAddPhotoName(false);
                                          setAddDesc(true);
                                          setAddListLink(false);
                                        }}
                                        // disabled={isLoading}
                                      >
                                        {"<- Back"}
                                      </button>
                                      <button
                                        className={`${style.btnNext}`}
                                        // onClick={handleSubmit}
                                        // disabled={isLoading}
                                      >
                                        {"Save"}
                                      </button>
                                    </div>
                                    {/* END OF BUTTON BACK OR SKIP AND SAVE */}
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </>
                    ) : null}
                  </div>
                </div>
              </div>
            </div>
          </section>
        </main>
      </>
    </div>
  );
}
