import React from "react";
import Head from "next/head";
import style from "@/styles/pages/editListLink.module.scss";
import Image from "next/image";
import { useRouter } from "next/router";
import axios from "axios";
import Link from "next/link";

// MATERIAL UI
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";

// ICON
import FacebookIcon from "@mui/icons-material/Facebook";
import GitHubIcon from "@mui/icons-material/GitHub";
import YouTubeIcon from "@mui/icons-material/YouTube";
import WhatsAppIcon from "@mui/icons-material/WhatsApp";
import TwitterIcon from "@mui/icons-material/Twitter";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import InstagramIcon from "@mui/icons-material/Instagram";

export default function Edit() {
  const router = useRouter();
  const [isLoading, setIsLoading] = React.useState(true);

  // STATE FOR ADD LINKPOCKET
  const [socmed, setSocmed] = React.useState({});
  // const [link, setLink] = React.useState([
  //   {
  //     link: "",
  //     title: "",
  //   },
  // ]);

  // STATE FOR EDIT
  const [slug, setSlug] = React.useState(``);
  const convertSlug = slug.split("-").slice(0, 2).join("-")

  // GET USER DATA
  React.useEffect(() => {
    axios
      .get(`${process.env.NEXT_PUBLIC_BACKEND_URL}/v1/space`, {
        headers: {
          Authorization: `Bearer ${localStorage.getItem("token")}`,
        },
      })
      .then(({ data }) => {
        // console.log(data?.data[0]?.title);
        const test = JSON.parse(data?.data[0]?.social_media);
        setSocmed(test);
        // setTitle(data?.data[0]?.title);
        // setPhoto(data?.data[0]?.photo_profile);
        setSlug(`${data?.data[0]?.slug}`);

        // setUploadImg(data?.data[0]?.photo_profile);
        // setPicture(data?.data[0]?.photo_profile);
      })
      .catch(() => setSocmed([]))
      .finally(() => {
        setIsLoading(false);
      });
  }, []);
  // console.log(facebook);

  // SAVE EDIT LINKPOCKET
  const sendData = () => {
    let bodyFormData = new FormData();
    setIsLoading(true);

    bodyFormData.append("social_media", JSON.stringify(socmed));
    // bodyFormData.append("link", JSON.stringify(link));

    axios
      .put(
        `${process.env.NEXT_PUBLIC_BACKEND_URL}/v1/space/${slug}`,
        bodyFormData,
        {
          headers: {
            "Content-Type": "multipart/form-data",
            Authorization: `Bearer ${localStorage?.getItem("token")}`,
          },
        }
      )
      .then(() => {
        router.push(`/profile/${convertSlug}`);
      })
      .finally(() => {
        // setIsLoading(false);
      });
  };

  return (
    <div>
      <Head>
        <title>Edit Link List | LinkPocket</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <section className={`container-fluid ${style.edit}`}>
          <div className={`container`}>
            <div className={`row`}>
              <div className={`col-12 p-0`}>
                <div
                  className={`d-flex justify-content-center align-items-center ${style.editSide}`}
                >
                  {/* CARD FORM EDIT USER */}
                  <div
                    className={`px-sm-5 px-4 py-sm-3 py-2 ${style.cardEdit}`}
                  >
                    {isLoading ? (
                      <div className="position-absolute top-50 start-50 translate-middle">
                        <div className="d-flex justify-content-center">
                          <Image
                            src={require("/public/images/Icon-app-nooutline.webp")}
                            className={` ${style.iconApp}`}
                            width={200}
                            // height={65}
                            alt="Icon-Linkpocket"
                          />
                        </div>
                        <div className="d-flex justify-content-center">
                          <div
                            class="spinner-border text-info "
                            style={{
                              width: "5rem",
                              height: "5rem",
                              margin: "auto",
                            }}
                            role="status"
                          >
                            <span class="visually-hidden ">Loading...</span>
                          </div>
                        </div>
                      </div>
                    ) : (
                      <>
                        {/* HEAD CARD */}
                        <div className="row">
                          <div className={`col-12 ${style.headCard}`}>
                            <div className="d-flex justify-content-center align-items-center">
                              <Image
                                src={require("/public/images/Icon-app-outline.webp")}
                                className={`${style.iconApp}`}
                                // width={500}
                                height={75}
                                alt="Icon-Linkpocket"
                              />
                            </div>
                            <div className="d-flex justify-content-center align-items-center">
                              <h1 className={`${style.Title}`}>
                                Edit Link List
                              </h1>
                            </div>
                            {/* INSTRUCTION */}
                            <div className="d-flex justify-content-center">
                              <p className={`${style.instruction}`}>
                                Add or remove your link
                              </p>
                            </div>
                          </div>
                        </div>
                        {/* END OF HEAD CARD */}

                        {/* FORM LINK SOCMED */}
                        <div className={`row ${style.linkSection}`}>
                          <div className="col-12">
                            <div className={`${style.formLink}`}>
                              <Box
                                sx={{
                                  "& > :not(style)": { m: 1 },
                                }}
                              >
                                {/* FACEBOOK */}
                                <Box
                                  sx={{
                                    display: "flex",
                                    alignItems: "flex-end",
                                    "& > :not(style)": { mb: 2 },
                                  }}
                                  style={{
                                    display: "flex",
                                    alignItems: "start",
                                  }}
                                >
                                  <FacebookIcon
                                    style={{
                                      color: "#4267B2",
                                      fontSize: "40px",
                                      marginRight: "5px",
                                    }}
                                  />
                                  <TextField
                                    className={style.formFb}
                                    id="outlined-search"
                                    label="Facebook"
                                    fullWidth
                                    multiline
                                    focused={socmed.facebook}
                                    maxRows={3}
                                    size="small"
                                    type="Required"
                                    inputProps={{
                                      style: {
                                        color: "white",
                                      },
                                    }}
                                    sx={{
                                      "& label": {
                                        color: "white",
                                      },
                                      "& label.Mui-focused": {
                                        color: "#03e9f4",
                                      },
                                      "& .MuiInput-underline:after": {
                                        borderBottomColor: "#03e9f4",
                                      },
                                      "& .MuiOutlinedInput-root": {
                                        "& fieldset": {
                                          borderColor: "white",
                                        },
                                        "&:hover fieldset": {
                                          borderColor: "white",
                                        },
                                        "&.Mui-focused fieldset": {
                                          borderColor: "#03e9f4",
                                        },
                                      },
                                    }}
                                    defaultValue={socmed.facebook}
                                    onChange={(e) => {
                                      setSocmed({
                                        facebook: e.target.value,
                                        instagram: socmed.instagram,
                                        tiktok: socmed.tiktok,
                                        whatsapp: socmed.whatsapp,
                                        youtube: socmed.youtube,
                                        twitter: socmed.twitter,
                                        github: socmed.github,
                                        linkedin: socmed.linkedin,
                                        shopee: socmed.shopee,
                                      });
                                    }}
                                  />
                                </Box>

                                {/* INSTAGRAM */}
                                <Box
                                  sx={{
                                    display: "flex",
                                    alignItems: "flex-end",
                                    "& > :not(style)": { mb: 2 },
                                  }}
                                  style={{
                                    display: "flex",
                                    alignItems: "start",
                                  }}
                                >
                                  <InstagramIcon
                                    style={{
                                      color: "#E1306C",
                                      fontSize: "40px",
                                      marginRight: "5px",
                                    }}
                                  />
                                  <TextField
                                    id="outlined-search"
                                    label="Instagram"
                                    fullWidth
                                    multiline
                                    focused={socmed.instagram}
                                    maxRows={3}
                                    size="small"
                                    type="Required"
                                    inputProps={{
                                      style: {
                                        color: "white",
                                      },
                                    }}
                                    sx={{
                                      "& label": {
                                        color: "white",
                                      },
                                      "& label.Mui-focused": {
                                        color: "#03e9f4",
                                      },
                                      "& .MuiInput-underline:after": {
                                        borderBottomColor: "#03e9f4",
                                      },
                                      "& .MuiOutlinedInput-root": {
                                        "& fieldset": {
                                          borderColor: "white",
                                        },
                                        "&:hover fieldset": {
                                          borderColor: "white",
                                        },
                                        "&.Mui-focused fieldset": {
                                          borderColor: "#03e9f4",
                                        },
                                      },
                                    }}
                                    defaultValue={socmed.instagram}
                                    onChange={(e) => {
                                      setSocmed({
                                        facebook: socmed.facebook,
                                        instagram: e.target.value,
                                        tiktok: socmed.tiktok,
                                        whatsapp: socmed.whatsapp,
                                        youtube: socmed.youtube,
                                        twitter: socmed.twitter,
                                        github: socmed.github,
                                        linkedin: socmed.linkedin,
                                        shopee: socmed.shopee,
                                      });
                                    }}
                                  />
                                </Box>

                                {/* TIKTOK */}
                                <Box
                                  sx={{
                                    display: "flex",
                                    alignItems: "flex-end",
                                    "& > :not(style)": { mb: 2 },
                                  }}
                                  style={{
                                    display: "flex",
                                    alignItems: "start",
                                  }}
                                >
                                  <Image
                                    src={require("../../../../public/images/icon-tiktok.webp")}
                                    className={`${style.iconSocmed}`}
                                    style={{
                                      marginRight: "6px",
                                      marginLeft: "2px",
                                    }}
                                    // width={500}
                                    height={37}
                                    alt="Icon-Linkpocket"
                                  />
                                  <TextField
                                    id="outlined-search"
                                    label="TikTok"
                                    fullWidth
                                    multiline
                                    focused={socmed.tiktok}
                                    maxRows={3}
                                    size="small"
                                    type="Required"
                                    inputProps={{
                                      style: {
                                        color: "white",
                                      },
                                    }}
                                    sx={{
                                      "& label": {
                                        color: "white",
                                      },
                                      "& label.Mui-focused": {
                                        color: "#03e9f4",
                                      },
                                      "& .MuiInput-underline:after": {
                                        borderBottomColor: "#03e9f4",
                                      },
                                      "& .MuiOutlinedInput-root": {
                                        "& fieldset": {
                                          borderColor: "white",
                                        },
                                        "&:hover fieldset": {
                                          borderColor: "white",
                                        },
                                        "&.Mui-focused fieldset": {
                                          borderColor: "#03e9f4",
                                        },
                                      },
                                    }}
                                    defaultValue={socmed.tiktok}
                                    onChange={(e) => {
                                      setSocmed({
                                        facebook: socmed.facebook,
                                        instagram: socmed.instagram,
                                        tiktok: e.target.value,
                                        whatsapp: socmed.whatsapp,
                                        youtube: socmed.youtube,
                                        twitter: socmed.twitter,
                                        github: socmed.github,
                                        linkedin: socmed.linkedin,
                                        shopee: socmed.shopee,
                                      });
                                    }}
                                  />
                                </Box>

                                {/* WHATSAPP */}
                                <Box
                                  sx={{
                                    display: "flex",
                                    alignItems: "flex-end",
                                    "& > :not(style)": { mb: 2 },
                                  }}
                                  style={{
                                    display: "flex",
                                    alignItems: "start",
                                  }}
                                >
                                  <WhatsAppIcon
                                    style={{
                                      color: "#25D366",
                                      fontSize: "40px",
                                      marginRight: "5px",
                                    }}
                                  />
                                  <TextField
                                    id="outlined-search"
                                    label="WhatsApp"
                                    fullWidth
                                    multiline
                                    focused={socmed.whatsapp}
                                    maxRows={3}
                                    size="small"
                                    type="Required"
                                    inputProps={{
                                      style: {
                                        color: "white",
                                      },
                                    }}
                                    sx={{
                                      "& label": {
                                        color: "white",
                                      },
                                      "& label.Mui-focused": {
                                        color: "#03e9f4",
                                      },
                                      "& .MuiInput-underline:after": {
                                        borderBottomColor: "#03e9f4",
                                      },
                                      "& .MuiOutlinedInput-root": {
                                        "& fieldset": {
                                          borderColor: "white",
                                        },
                                        "&:hover fieldset": {
                                          borderColor: "white",
                                        },
                                        "&.Mui-focused fieldset": {
                                          borderColor: "#03e9f4",
                                        },
                                      },
                                    }}
                                    defaultValue={socmed.whatsapp}
                                    onChange={(e) => {
                                      setSocmed({
                                        facebook: socmed.facebook,
                                        instagram: socmed.instagram,
                                        tiktok: socmed.tiktok,
                                        whatsapp: e.target.value,
                                        youtube: socmed.youtube,
                                        twitter: socmed.twitter,
                                        github: socmed.github,
                                        linkedin: socmed.linkedin,
                                        shopee: socmed.shopee,
                                      });
                                    }}
                                  />
                                </Box>

                                {/* YOUTUBE */}
                                <Box
                                  sx={{
                                    display: "flex",
                                    alignItems: "flex-end",
                                    "& > :not(style)": { mb: 2 },
                                  }}
                                  style={{
                                    display: "flex",
                                    alignItems: "start",
                                  }}
                                >
                                  <YouTubeIcon
                                    style={{
                                      color: "#FF0000",
                                      fontSize: "40px",
                                      marginRight: "5px",
                                    }}
                                  />
                                  <TextField
                                    id="outlined-search"
                                    label="YouTube"
                                    fullWidth
                                    multiline
                                    focused={socmed.youtube}
                                    maxRows={3}
                                    size="small"
                                    type="Required"
                                    inputProps={{
                                      style: {
                                        color: "white",
                                      },
                                    }}
                                    sx={{
                                      "& label": {
                                        color: "white",
                                      },
                                      "& label.Mui-focused": {
                                        color: "#03e9f4",
                                      },
                                      "& .MuiInput-underline:after": {
                                        borderBottomColor: "#03e9f4",
                                      },
                                      "& .MuiOutlinedInput-root": {
                                        "& fieldset": {
                                          borderColor: "white",
                                        },
                                        "&:hover fieldset": {
                                          borderColor: "white",
                                        },
                                        "&.Mui-focused fieldset": {
                                          borderColor: "#03e9f4",
                                        },
                                      },
                                    }}
                                    defaultValue={socmed.youtube}
                                    onChange={(e) => {
                                      setSocmed({
                                        facebook: socmed.facebook,
                                        instagram: socmed.instagram,
                                        tiktok: socmed.tiktok,
                                        whatsapp: socmed.whatsapp,
                                        youtube: e.target.value,
                                        twitter: socmed.twitter,
                                        github: socmed.github,
                                        linkedin: socmed.linkedin,
                                        shopee: socmed.shopee,
                                      });
                                    }}
                                  />
                                </Box>

                                {/* TWITTER */}
                                <Box
                                  sx={{
                                    display: "flex",
                                    alignItems: "flex-end",
                                    "& > :not(style)": { mb: 2 },
                                  }}
                                  style={{
                                    display: "flex",
                                    alignItems: "start",
                                  }}
                                >
                                  <TwitterIcon
                                    style={{
                                      color: "#1DA1F2",
                                      fontSize: "40px",
                                      marginRight: "5px",
                                    }}
                                  />
                                  <TextField
                                    id="outlined-search"
                                    label="Twitter"
                                    fullWidth
                                    multiline
                                    focused={socmed.twitter}
                                    maxRows={3}
                                    size="small"
                                    type="Required"
                                    inputProps={{
                                      style: {
                                        color: "white",
                                      },
                                    }}
                                    sx={{
                                      "& label": {
                                        color: "white",
                                      },
                                      "& label.Mui-focused": {
                                        color: "#03e9f4",
                                      },
                                      "& .MuiInput-underline:after": {
                                        borderBottomColor: "#03e9f4",
                                      },
                                      "& .MuiOutlinedInput-root": {
                                        "& fieldset": {
                                          borderColor: "white",
                                        },
                                        "&:hover fieldset": {
                                          borderColor: "white",
                                        },
                                        "&.Mui-focused fieldset": {
                                          borderColor: "#03e9f4",
                                        },
                                      },
                                    }}
                                    defaultValue={socmed.twitter}
                                    onChange={(e) => {
                                      setSocmed({
                                        facebook: socmed.facebook,
                                        instagram: socmed.instagram,
                                        tiktok: socmed.tiktok,
                                        whatsapp: socmed.whatsapp,
                                        youtube: socmed.youtube,
                                        twitter: e.target.value,
                                        github: socmed.github,
                                        linkedin: socmed.linkedin,
                                        shopee: socmed.shopee,
                                      });
                                    }}
                                  />
                                </Box>

                                {/* GITHUB */}
                                <Box
                                  sx={{
                                    display: "flex",
                                    alignItems: "flex-end",
                                    "& > :not(style)": { mb: 2 },
                                  }}
                                  style={{
                                    display: "flex",
                                    alignItems: "start",
                                  }}
                                >
                                  <GitHubIcon
                                    style={{
                                      color: "#333",
                                      fontSize: "40px",
                                      marginRight: "5px",
                                    }}
                                  />
                                  <TextField
                                    id="outlined-search"
                                    label="GitHub"
                                    fullWidth
                                    multiline
                                    focused={socmed.github}
                                    maxRows={3}
                                    size="small"
                                    type="Required"
                                    inputProps={{
                                      style: {
                                        color: "white",
                                      },
                                    }}
                                    sx={{
                                      "& label": {
                                        color: "white",
                                      },
                                      "& label.Mui-focused": {
                                        color: "#03e9f4",
                                      },
                                      "& .MuiInput-underline:after": {
                                        borderBottomColor: "#03e9f4",
                                      },
                                      "& .MuiOutlinedInput-root": {
                                        "& fieldset": {
                                          borderColor: "white",
                                        },
                                        "&:hover fieldset": {
                                          borderColor: "white",
                                        },
                                        "&.Mui-focused fieldset": {
                                          borderColor: "#03e9f4",
                                        },
                                      },
                                    }}
                                    defaultValue={socmed.github}
                                    onChange={(e) => {
                                      setSocmed({
                                        facebook: socmed.facebook,
                                        instagram: socmed.instagram,
                                        tiktok: socmed.tiktok,
                                        whatsapp: socmed.whatsapp,
                                        youtube: socmed.youtube,
                                        twitter: socmed.twitter,
                                        github: e.target.value,
                                        linkedin: socmed.linkedin,
                                        shopee: socmed.shopee,
                                      });
                                    }}
                                  />
                                </Box>

                                {/* LINKEDIN */}
                                <Box
                                  sx={{
                                    display: "flex",
                                    alignItems: "flex-end",
                                    "& > :not(style)": { mb: 2 },
                                  }}
                                  style={{
                                    display: "flex",
                                    alignItems: "start",
                                  }}
                                >
                                  <LinkedInIcon
                                    style={{
                                      color: "#0072b1",
                                      fontSize: "40px",
                                      marginRight: "5px",
                                    }}
                                  />
                                  <TextField
                                    id="outlined-search"
                                    label="LinkedIn"
                                    fullWidth
                                    multiline
                                    focused={socmed.linkedin}
                                    maxRows={3}
                                    size="small"
                                    type="Required"
                                    inputProps={{
                                      style: {
                                        color: "white",
                                      },
                                    }}
                                    sx={{
                                      "& label": {
                                        color: "white",
                                      },
                                      "& label.Mui-focused": {
                                        color: "#03e9f4",
                                      },
                                      "& .MuiInput-underline:after": {
                                        borderBottomColor: "#03e9f4",
                                      },
                                      "& .MuiOutlinedInput-root": {
                                        "& fieldset": {
                                          borderColor: "white",
                                        },
                                        "&:hover fieldset": {
                                          borderColor: "white",
                                        },
                                        "&.Mui-focused fieldset": {
                                          borderColor: "#03e9f4",
                                        },
                                      },
                                    }}
                                    defaultValue={socmed.linkedin}
                                    onChange={(e) => {
                                      setSocmed({
                                        facebook: socmed.facebook,
                                        instagram: socmed.instagram,
                                        tiktok: socmed.tiktok,
                                        whatsapp: socmed.whatsapp,
                                        youtube: socmed.youtube,
                                        twitter: socmed.twitter,
                                        github: socmed.github,
                                        linkedin: e.target.value,
                                        shopee: socmed.shopee,
                                      });
                                    }}
                                  />
                                </Box>

                                {/* SHOPEE */}
                                <Box
                                  sx={{
                                    display: "flex",
                                    alignItems: "flex-end",
                                    "& > :not(style)": { mb: 2 },
                                  }}
                                  style={{
                                    display: "flex",
                                    alignItems: "start",
                                  }}
                                >
                                  <Image
                                    src={require("../../../../public/images/icon-sp.webp")}
                                    className={`${style.iconSocmed}`}
                                    style={{ marginRight: "5px" }}
                                    // width={500}
                                    height={40}
                                    alt="Icon-Linkpocket"
                                  />
                                  <TextField
                                    id="outlined-search"
                                    label="Shopee"
                                    fullWidth
                                    multiline
                                    focused={socmed.shopee}
                                    maxRows={3}
                                    size="small"
                                    type="Required"
                                    inputProps={{
                                      style: {
                                        color: "white",
                                      },
                                    }}
                                    sx={{
                                      "& label": {
                                        color: "white",
                                      },
                                      "& label.Mui-focused": {
                                        color: "#03e9f4",
                                      },
                                      "& .MuiInput-underline:after": {
                                        borderBottomColor: "#03e9f4",
                                      },
                                      "& .MuiOutlinedInput-root": {
                                        "& fieldset": {
                                          borderColor: "white",
                                        },
                                        "&:hover fieldset": {
                                          borderColor: "white",
                                        },
                                        "&.Mui-focused fieldset": {
                                          borderColor: "#03e9f4",
                                        },
                                      },
                                    }}
                                    defaultValue={socmed.shopee}
                                    onChange={(e) => {
                                      setSocmed({
                                        facebook: socmed.facebook,
                                        instagram: socmed.instagram,
                                        tiktok: socmed.tiktok,
                                        whatsapp: socmed.whatsapp,
                                        youtube: socmed.youtube,
                                        twitter: socmed.twitter,
                                        github: socmed.github,
                                        linkedin: socmed.linkedin,
                                        shopee: e.target.value,
                                      });
                                    }}
                                  />
                                </Box>

                                <style>
                                  {`
                                ::-webkit-scrollbar {
                                  width: 0em;
                                  height: 0.5em;
                                }
                                ::-webkit-scrollbar-thumb {
                                  background-color: rgba(0, 0, 0, 0.2);
                                }
                              `}
                                </style>
                              </Box>
                            </div>
                          </div>
                        </div>
                        {/* END OF FORM LINK SOCMED */}

                        {/* BUTTON SAVE EDIT */}
                        <div className="row">
                          <div className={`col-12 ${style.button}`}>
                            <div className="mt-4 d-flex justify-content-end">
                              <Link
                                className={`btn ${style.btnCancel}`}
                                onClick={() => {
                                  setIsLoading(true);
                                }}
                                href={`/profile/${convertSlug}`}
                              >
                                {"Cancel"}
                              </Link>
                              <button
                                className={`btn ${style.btnSave}`}
                                onClick={() => {
                                  sendData();
                                }}
                              >
                                {"Save"}
                              </button>
                            </div>
                          </div>
                        </div>
                        {/* END OF BUTTON SAVE EDIT */}
                      </>
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
